"""add_vacation

Revision ID: 2bb3cc1835c2
Revises: d55be4713c22
Create Date: 2024-12-15 16:53:57.218070

"""

import sqlalchemy as sa
from alembic import op

from app.model.base import CustomUUID


# revision identifiers, used by Alembic.
revision = "2bb3cc1835c2"
down_revision = "d55be4713c22"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacation",
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("total_work_days", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("PAID", "UNPAID", name="vacationtype"), nullable=False
        ),
        sa.Column("employee_id", CustomUUID(), nullable=False),
        sa.Column("id", CustomUUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"], ["employee.id"], name="vacation_employee_id_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vacation_id"), "vacation", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vacation_id"), table_name="vacation")
    op.drop_table("vacation")
    # ### end Alembic commands ###
