"""first_migration

Revision ID: 7f6b3e379e34
Revises:
Create Date: 2024-12-14 15:53:19.256506

"""

from alembic import op
import sqlalchemy as sa

from app.model.base import CustomUUID


# revision identifiers, used by Alembic.
revision = "7f6b3e379e34"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee",
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("id", CustomUUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employee_id"), "employee", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employee_id"), table_name="employee")
    op.drop_table("employee")
    # ### end Alembic commands ###
