"""create_team_migration

Revision ID: d55be4713c22
Revises: 7f6b3e379e34
Create Date: 2024-12-14 23:40:57.429492

"""

from alembic import op
from sqlalchemy import orm
import sqlalchemy as sa

from app.model.base import CustomUUID
from app.model.team import TeamModel


# revision identifiers, used by Alembic.
revision = "d55be4713c22"
down_revision = "7f6b3e379e34"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", CustomUUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_team_id"), "team", ["id"], unique=False)

    # Add default team
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    staff = TeamModel(name="General staff")
    session.add(staff)
    session.commit()

    op.add_column(
        "employee",
        sa.Column(
            "team_id", CustomUUID(), nullable=False, server_default=str(staff.id)
        ),
    )
    op.create_foreign_key(
        "employee_team_id_fk", "employee", "team", ["team_id"], ["id"]
    )

    session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("employee_team_id_fk", "employee", type_="foreignkey")
    op.drop_column("employee", "team_id")
    op.drop_index(op.f("ix_team_id"), table_name="team")
    op.drop_table("team")
    # ### end Alembic commands ###
